apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
  - name: {{ .Values.application.name }}
    protocol: TCP
    port: {{ .Values.svc.port }}
    targetPort: {{ .Values.svc.port }}
    nodePort: {{ .Values.svc.node.port }}