# Default values for iotapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  name: iot-test
  namespace:
    name: test-iot-app
  image: ghcr.io/djsasha777/iot/iot/iotbackend:0741895
  svc:
    port: 8008
    type: ClusterIP
    node:
      port: 30888
  replicaCount: 1
  ingress:
    host:
      name: "jadu.ga"

istio:
  ingress:
    svc:
      name: iot-istio-ingress
      port: 4000

integrations:
  - name: epk
    host: qwertyu.ru
    ip: 192.168.111.11
  - name: graphql
    host: malo.ru
    ip: 174.1.1.1
  - name: holdingcard
    host: holding.ru
    ip: 172.1.1.2