# Default values for iotapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  name: iot-test
  namespace:
    name: dev-iot-app
  image: ghcr.io/djsasha777/iot/iot/iotbackend:0741895
  svc:
    port: 8088
    type: ClusterIP
    node:
      port: 30888
  replicaCount: 1
  ingress:
    host:
      name: "jadu.ga"

configMap:
  - kakayatoperemennaya: dataone
  - vciakaya_fignia.yyy: mydata12345
  - perem-tree: dgkjfg
  - some-json: "{some json: 1234}"

integrations:
  - name: epk
    host: qwertyu.ru
    meshPort: 6666
    type: http
  - name: graphql
    host: malo.ru
    meshPort: 6667
    type: http
  - name: holdingcard
    host: holding.ru
    meshPort: 443
    type: https
    
istio:
  ingress:
    svc:
      name: iot-istio-ingress
      port: 4000
