architecture: replicaset
replicaCount: 2
volumePermissions: 
    enabled: true
persistence:
    size: 1Gi
#persistence:
#    storageClass: "linode-block-storage"
auth:
    rootPassword: secret-root-pwd
#auth:
#    usernames:
#    - djsasha777
#auth:
#    databases: 
#    - iotdatabase
