architecture: replicaset
replicaCount: 2
volumePermissions: 
    enabled: true
persistence:
    size: 1Gi
persistence:
    storageClass: "manual"
auth:
    rootPassword: secret-root-pwd
#auth:
#    usernames:
#    - djsasha777
#auth:
#    databases: 
#    - iotdatabase
