architecture: replicaset
replicaCount: 3
volumePermissions: 
    enabled: true
persistence:
    storageClass: "local-storage"
    size: 100Mi
auth:
    rootPassword: secret-root-pwd
#auth:
#    usernames:
#    - djsasha777
#auth:
#    databases: 
#    - iotdatabase
