kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-mongodb-0
  labels:
    type: local
spec:
  storageClassName:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/djsasha777/0"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-mongodb-1
  labels:
    type: local
spec:
  storageClassName:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/djsasha777/1"

