version: '3.7'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_BASICAUTH_USERNAME: djsasha777
      ME_CONFIG_BASICAUTH_PASSWORD: Fingaz3922
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: djsasha777
      ME_CONFIG_MONGODB_ADMINPASSWORD: Fingaz3922
    links:
      - mongo-db
    networks:
      - mongo-compose-network

  mongo-db:
    image: mongo
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: iotdatabase
      MONGO_INITDB_ROOT_USERNAME: djsasha777
      MONGO_INITDB_ROOT_PASSWORD: Fingaz3922
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge

volumes:
  mongodb_data_container: