apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: iotnamespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongo-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongo-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongo-cluster-role
subjects:
  - kind: ServiceAccount
    name: mongo
    namespace: mongo-state
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: iotnamespace
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: iotnamespace
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      serviceAccountName: mongo
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
          args:
            - "--replSet=rs0"
            - "--bind_ip=0.0.0.0"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
            - name: KUBERNETES_POD_LABELS
              value: "role=mongo,environment=test"
            - name: KUBERNETES_SERVICE_NAME
              value: "mongodb"
      volumes:
      - name: mongo-persistent-storage
        emptyDir: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: iotnamespace
type: Opaque
data:
  mongo-root-username: ZGpzYXNoYTc3Nw==
  mongo-root-password: RmluZ2F6MzkyMg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: iotnamespace
data:
  database_url: mongodb