apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: iotnamespace
data:
  database_url: mongodb-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: iotnamespace
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: iotnamespace
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployent
  namespace: iotnamespace
  labels:
    name: mymongo
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:
          - name: mongo-volume
            mountPath: /var/mongo/data
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-volume

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: iotnamespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: iotnamespace
type: Opaque
data:
  mongo-root-username: ZGpzYXNoYTc3Nw==
  mongo-root-password: RmluZ2F6MzkyMg==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
  namespace: iotnamespace
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi