
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-iot-run
  namespace: putradatabase
  labels:
    name: myappiotimage
    app: myappiotimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappiotimage
  template:
    metadata:
      labels:
        app: myappiotimage
    spec:
      containers:
      - name: myappiotimage
        image: djsasha777/iotimage:lts
        ports:
        - containerPort: 8088
        env:
        - name: MONGO_MONGODB_USERNAME
          value: "drage"
        - name: MONGO_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-password
        - name: MONGO_MONGODB_SERVER
          value: mongodb-0.mongodb-headless.iotdatabase
        - name: MONGO_MONGODB_DATABASE
          value: inventory

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: putradatabase
  labels:
    name: myappiotimage
    app: myappiotimage
spec:
  selector:
    app: myappiotimage
  type: LoadBalancer
  ports:
  - name: myappserviceport
    protocol: TCP
    port: 8088
    targetPort: 8088
    nodePort: 30888

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-iot-service-monitor
  namespace: putradatabase
  labels:
    release: stable
    app: myappiotimage
spec:
  endpoints:
    - path: /metrics
      port: myappserviceport
      targetPort: 8088
  namespaceSelector:
    matchNames:
    - putradatabase
  selector:
    matchLabels:
      app: myappiotimage

