---
- name: Start docker container
  hosts: nodes
  become: true
  tasks:
    - name: git pull project
      git:
        repo: 'https://github.com/djsasha777/iot.git'
        dest: /home/iot/
        clone: yes
        update: yes
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /home/iot/
        state: absent
    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/iot/
      register: output