apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace.name }}
  labels:
    app: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  type: {{ .Values.application.svc.type }}
  ports:
  - name: {{ .Values.application.name }}-svc-port
    protocol: TCP
    port: {{ .Values.application.svc.port }}
    targetPort: {{ .Values.application.svc.port }}