apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-iot-run
  labels:
    name: myappiotimage
    app: myappiotimage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myappiotimage
  template:
    metadata:
      labels:
        app: myappiotimage
    spec:
      containers:
      - name: myappiotimage
        image: ghcr.io/djsasha777/iot/iot/iotbackend:0741895
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 8088
        env:
        - name: MONGO_MONGODB_USERNAME
          value: root
        - name: MONGO_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        - name: MONGO_MONGODB_SERVER
          value: mongodb-0
        - name: MONGO_MONGODB_DATABASE
          value: iotdatabase





