--- 
apiVersion: v1
kind: Service
metadata:
  name: my-angular-service
  labels:
    name: angular
    app: angular
spec:
  selector:
    app: angular
  type: ClusterIP
  ports:
  - name: angularserviceport
    protocol: TCP
    port: 80
    targetPort: 8013
    #nodePort: 30508