---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-depl
  labels:
    name: angular
    app: angular
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angularimage
        image: ghcr.io/djsasha777/angular-react-starter/testtaskangular:5
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: my-angular-service
  labels:
    name: angular
    app: angular
spec:
  selector:
    app: angular
  type: LoadBalancer
  ports:
  - name: angularserviceport
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30508

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
      - jadu.ga
      secretName: angular-tls
  rules:
  - host: "jadu.ga"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-angular-service
            port:
              number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: spongermanalex@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
--- 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: spongermanalex@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
