# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "true"
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: mongo-volume-mongo-0
#   labels:
#     type: local
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 100Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/home/iot/mongo/0"

# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: mongo-volume-mongo-1
#   labels:
#     type: local
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 100Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/home/iot/mongo/1"

# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: mongo-volume-mongo-2
#   labels:
#     type: local
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 100Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/home/iot/mongo/2"

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "true"
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-volume-mongo-0
  labels:
    type: local
spec:
  storageClassName: 1s-microk8s-hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iot/mongo/0"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-volume-mongo-1
  labels:
    type: local
spec:
  storageClassName: 1s-microk8s-hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iot/mongo/1"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-volume-mongo-2
  labels:
    type: local
spec:
  storageClassName: 1s-microk8s-hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iot/mongo/2"