{{- range $integrations := .Values.integrations }}
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ $integrations.name }}
spec:
  host: {{ $integrations.host }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
{{- end }} 