{{- range $integrations := .Values.integrations }}  
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ $integrations.name }}
spec:
  hosts:
  - {{ $integrations.host }}
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
{{- end }} 